version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  app:
    image: dockerize
    container_name: app
    ports:
      - '3000:3000'
      - '5173:5173'
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017

volumes:
  mongo-data: